language: ruby
rvm:
  - 2.4.1

before_script:
 - chmod +x ./script/ci

script: ./script/ci

branches:
  only:
  - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false

cache: bundler # caching bundler gem packages will speed up build

notifications:
  email: false
