asset_path: /assets

title: Kuri Robot Documentation
description: Documentation & developer resources for Kuri robot
url: "https://" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

source: source/
destination: __public__/
plugins_dir: plugins/

# Build settings
plugins:
  - jekyll-feed

debug: true

sass:
  sass_dir: _sass
  style: compressed

markdown: CustomMarkdownParser
markdown_ext: md

collections:
  guides:
    output: true
    permalink: /guides/:path
  reference:
    output: true
    permalink: /reference/:path/
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
