title: Kuri Robot Documentation
description: Documentation & developer resources for Kuri robot
url: "https://kurirobot.io"
baseurl: "" # the subpath of your site, e.g. /blog

source: source/
destination: __public__/
plugins_dir: /plugins

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - rouge

debug: true

sass:
  load_paths:
    - ../vendor/bundle/ruby/2.5.0/gems/bootstrap-4.1.3/assets/stylesheets
    - ../_sass
  style: compressed

verbose: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
