title: Kuri Robot Documentation
description: Documentation & developer resources for Kuri robot
url: "https://kurirobot.io"
baseurl: "" # the subpath of your site, e.g. /blog

destination: __public__/
plugins_dir: /plugins

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-toc
  - rouge

debug: true
verbose: true

markdown: redcarpet
highlighter: rouge
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks",
               "disable_indented_code_blocks",
               "footnotes", "tables", "autolink"]

toc:
  min_level: 2
  max_level: 6

collections:
  guides:
    output: true
    permalink: /:collection/:categories/:name
  reference:
    output: true
    permalink: /:collection/:name

assets:
  source_maps: true # false on JEKYLL_ENV=production
  destination: "/assets"
  compression: false # true on JEKYLL_ENV=production
  gzip: false
  defaults:
    js: { integrity: false } # true on JEKYLL_ENV=production
    css: { integrity: false } # true on JEKYLL_ENV=production
    img: { integrity: false } # true on JEKYLL_ENV=production
  caching:
    path: ".jekyll-cache/assets"
    type: file # Possible values: memory, file
    enabled: true
  # --
  # Assets you wish to always have compiled.
  #   This can also be combined with raw_precompile which
  #   copies assets without running through the pipeline
  #   making them ultra fast.
  # --
  precompile: []
  raw_precompile: [
    #
  ]
  # --
  # baseurl: whether or not to append site.baseurl
  # destination: the folder you store them in on the CDN.
  # url: the CDN url (fqdn, or w/ identifier).
  # --
  cdn:
    baseurl: false
    destination: false
    url: null
  # --
  # These are all default. No need to add them
  #   Only use this if you have more.
  # --
  sources:
  - assets/css
  - assets/fonts
  - assets/images
  - assets/videos
  - assets/js
  - _assets/css
  - _assets/fonts
  - _assets/images
  - _assets/videos
  - _assets/js
  - _sass
  plugins:
    css: { autoprefixer: {}}
    img: { optim: {}}

# Exclude from processing.
exclude:
  - .idea
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
